CREATE DATABASE app DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER app_admin IDENTIFIED BY 'passadmit';

GRANT ALL PRIVILEGES ON app.* TO app_admin;

FLUSH PRIVILEGES;
